<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getUniqueStringList</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCi8vIFJl
dHJpZXZlIHRoZSBpbnB1dCBTdHJpbmdMaXN0ClN0cmluZ1tdIHN0cmluZ0xpc3QgPSBudWxsOwpp
ZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoInN0cmluZ0xpc3QiKSkgewogICAgc3RyaW5nTGlzdCA9
IChTdHJpbmdbXSkgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsKfQoKLy8gQ2hlY2sgaWYgc3Ry
aW5nTGlzdCBpcyBudWxsCmlmIChzdHJpbmdMaXN0ID09IG51bGwpIHsKICAgIC8vIFJldHVybiBh
biBlbXB0eSBsaXN0IGlmIHRoZSBpbnB1dCBpcyBudWxsCiAgICBzdHJpbmdMaXN0ID0gbmV3IFN0
cmluZ1swXTsKfQoKLy8gVXNlIGEgU2V0IHRvIGdldCB1bmlxdWUgdmFsdWVzClNldDxTdHJpbmc+
IHVuaXF1ZVNldCA9IG5ldyBIYXNoU2V0PD4oQXJyYXlzLmFzTGlzdChzdHJpbmdMaXN0KSk7Cgov
LyBDb252ZXJ0IFNldCBiYWNrIHRvIFN0cmluZ0xpc3QKU3RyaW5nW10gdW5pcXVlU3RyaW5nTGlz
dCA9IHVuaXF1ZVNldC50b0FycmF5KG5ldyBTdHJpbmdbMF0pOwoKLy8gU2V0IHRoZSBvdXRwdXQg
U3RyaW5nTGlzdCBpbiB0aGUgcGlwZWxpbmUKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwg
InVuaXF1ZVN0cmluZ0xpc3QiLCB1bmlxdWVTdHJpbmdMaXN0KTsKCi8vIERlc3Ryb3kgdGhlIGN1
cnNvcgpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7Cgk=</value>
</Values>
