<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getUniqueStringList</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCi8vIFJl
dHJpZXZlIHRoZSBpbnB1dCBTdHJpbmdMaXN0ClN0cmluZ1tdIHN0cmluZ0xpc3QgPSBudWxsOwpp
ZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoInN0cmluZ0xpc3QiKSkgewogICAgc3RyaW5nTGlzdCA9
IChTdHJpbmdbXSkgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsKfSAKCi8vIENoZWNrIGlmIHN0
cmluZ0xpc3QgaXMgbnVsbAppZiAoc3RyaW5nTGlzdCA9PSBudWxsKSB7CiAgICAvLyBSZXR1cm4g
YW4gZW1wdHkgbGlzdCBpZiB0aGUgaW5wdXQgaXMgbnVsbAogICAgc3RyaW5nTGlzdCA9IG5ldyBT
dHJpbmdbMF07Cn0KCi8vIFVzZSBhIFNldCB0byBnZXQgdW5pcXVlIHZhbHVlcwpTZXQ8U3RyaW5n
PiB1bmlxdWVTZXQgPSBuZXcgSGFzaFNldDw+KEFycmF5cy5hc0xpc3Qoc3RyaW5nTGlzdCkpOwoK
Ly8gQ29udmVydCBTZXQgYmFjayB0byBTdHJpbmdMaXN0ClN0cmluZ1tdIHVuaXF1ZVN0cmluZ0xp
c3QgPSB1bmlxdWVTZXQudG9BcnJheShuZXcgU3RyaW5nWzBdKTsKCi8vIFNldCB0aGUgb3V0cHV0
IFN0cmluZ0xpc3QgaW4gdGhlIHBpcGVsaW5lCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3Is
ICJ1bmlxdWVTdHJpbmdMaXN0IiwgdW5pcXVlU3RyaW5nTGlzdCk7CgovLyBEZXN0cm95IHRoZSBj
dXJzb3IKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoJ</value>
</Values>
